title: 추승우
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

gems: ['jekyll-multiple-languages']
languages: ['ko', 'en']
language_default: 'ko'
fill_default_content: true

url: http://sungwoo.me
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

social:
   github: kswchoo
   twitter: kswchoo
   facebook: kswchoo
   email: choo@sungwoo.me

navigation:
    - title: 연락하기
      title_en: Contact
      url: contact
    - title: 걸어온 길
      title_en: Curriculum vitae
      url: cv

google_analytics: ""



